version: "3.8"

services:

  db:
    container_name: "mysql"
    image: "mysql:5.7"
    ports: 
      - "3306:3306"
    volumes:
      - "/opt/hua_project/hermes/mysql:/var/lib/mysql"
    environment: 
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
    networks: 
      - backend
    restart: always

  keycloak:
    container_name: "keycloak"
    depends_on: 
      - db
    image: "europe-west2-docker.pkg.dev/hua-hermes/keycloak/keycloak-dev:latest"
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_ADDR: mysql
      DB_VENDOR: mysql
      DB_USER: root
      DB_PASSWORD: root
    networks: 
      backend:
    restart: always

networks: 
  backend: