keycloak:
  auth-server-url: http://${KEYCLOAK_URL}/auth
  realm: hermes
  resource: backend
  principal-attribute: preferred_username
  bearer-only: true
spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/${DB_SCHEMA}?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update #Normally not used in production - but our back-end is really small
server:
  error:
    include-stacktrace: never #Prevent sensitive info exposure
    include-message: never #Prevent sensitive info exposure
logging:
  level:
    root: info
