keycloak:
  realm: hermes
  resource: backend
  principal-attribute: preferred_username
  bearer-only: true
spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/${DB_SCHEMA}?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update #Normally not used in production - but our back-end is really small
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
server:
  error:
    include-stacktrace: never #Prevent sensitive info exposure
    include-message: never #Prevent sensitive info exposure
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: 'health'
  server:
    port: 9001